const padTo200 = (list) => {
  const result = [...list];
  let idx = 0;
  while (result.length < 200) {
    result.push(list[idx % list.length]);
    idx += 1;
  }
  return result.slice(0, 200);
};

const cryptoBase = [
  'BTC/USD','ETH/USD','BNB/USD','SOL/USD','XRP/USD','ADA/USD','DOGE/USD','AVAX/USD','TRX/USD','DOT/USD','MATIC/USD','LTC/USD','LINK/USD','BCH/USD','XLM/USD','ATOM/USD','ICP/USD','OP/USD','ARB/USD','APT/USD','NEAR/USD','ETC/USD','HBAR/USD','VET/USD','FTM/USD','SAND/USD','MANA/USD','AAVE/USD','UNI/USD','DYDX/USD','GMX/USD','IMX/USD','INJ/USD','RUNE/USD','CRV/USD','COMP/USD','SNX/USD','ALGO/USD','EGLD/USD','AXS/USD','FLOW/USD','MINA/USD','GRT/USD','RPL/USD','MKR/USD','LDO/USD','1INCH/USD','BAT/USD','ZRX/USD','CELO/USD','KAVA/USD','KLAY/USD','STX/USD','THETA/USD','FIL/USD','RNDR/USD','PEPE/USD','FTT/USD','QTUM/USD','NEO/USD','AR/USD','WAVES/USD','CAKE/USD','KSM/USD','DASH/USD','ZEC/USD','CHZ/USD','ENJ/USD','XEM/USD','ONT/USD','RVN/USD','XEC/USD','CSPR/USD','XMR/USD','BTG/USD','BTT/USD','YFI/USD','BAL/USD','GALA/USD','AGIX/USD','ROSE/USD','CFX/USD','FLUX/USD','KDA/USD','LRC/USD','SKL/USD','ANKR/USD','ENS/USD','SUI/USD','SEI/USD','BLUR/USD','TIA/USD','PYTH/USD','JTO/USD','BONK/USD','TWT/USD','ASTR/USD','OCEAN/USD','IOST/USD','ICX/USD','CELR/USD','ANT/USD','APTOS/USD','WOO/USD','OSMO/USD','ZIL/USD','STORJ/USD','GNO/USD','RSR/USD','HOT/USD','MXC/USD','BAND/USD','ILV/USD','LSK/USD','KNC/USD','COTI/USD','BTM/USD','ZEN/USD','ARDR/USD','HNT/USD','GLM/USD','AMP/USD','NXM/USD','UMA/USD','ALPHA/USD','SXP/USD','FXS/USD','FXN/USD','LUNA/USD','LUNC/USD','USTC/USD'
];

const trStockBase = [
  'BIST:AKBNK','BIST:ISCTR','BIST:YKBNK','BIST:SAHOL','BIST:GARAN','BIST:ASELS','BIST:KRDMD','BIST:EREGL','BIST:PETKM','BIST:TUPRS','BIST:THYAO','BIST:BIMAS','BIST:TOASO','BIST:TCELL','BIST:KCHOL','BIST:SISE','BIST:FROTO','BIST:HEKTS','BIST:AEFES','BIST:KOZAL','BIST:DOHOL','BIST:VESBE','BIST:ENKAI','BIST:MGROS','BIST:SOKM','BIST:PGSUS','BIST:KONTR','BIST:OYAKC','BIST:TTRAK','BIST:ALKIM','BIST:ALARK','BIST:AKSEN','BIST:CEMTS','BIST:KORDS','BIST:SAHOL','BIST:ENJSA','BIST:VESTL','BIST:LOGO','BIST:OTKAR','BIST:ANACM','BIST:ULKER','BIST:AGHOL','BIST:OTKAR','BIST:SISE','BIST:ARCLK','BIST:AYDEM','BIST:BRISA','BIST:GOZDE','BIST:QUAGR','BIST:DEVA','BIST:KRGYO','BIST:SASA','BIST:GUBRF','BIST:ISDMR','BIST:HUBVC','BIST:KZBGY','BIST:NTHOL','BIST:NETAS','BIST:SELEC','BIST:KFEIN','BIST:PETUN','BIST:OYYAT','BIST:IZMDC','BIST:AKFGY','BIST:GLYHO','BIST:KTSKR','BIST:KRONT','BIST:TKFEN','BIST:TRGYO','BIST:TSPOR','BIST:KARYE','BIST:TUCLK','BIST:OYAYO','BIST:CANTE','BIST:ISMEN','BIST:HLGYO','BIST:KUVVA','BIST:ULUUN','BIST:GESAN','BIST:GSDHO','BIST:HEDEF','BIST:KTLEV','BIST:SMRTG','BIST:ATEKS','BIST:AYGAZ','BIST:RALYH','BIST:EUHOL','BIST:ICBCT','BIST:VAKBN','BIST:AKBNK.PR','BIST:ISCTR.PR'
];

const forexBase = [
  'EUR/USD','USD/TRY','EUR/TRY','GBP/USD','USD/JPY','USD/CHF','AUD/USD','USD/CAD','NZD/USD','EUR/GBP','EUR/CHF','GBP/JPY','AUD/JPY','CHF/JPY','EUR/AUD','EUR/CAD','GBP/CHF','GBP/AUD','USD/SEK','USD/NOK','USD/DKK','USD/MXN','USD/ZAR','USD/PLN','USD/RUB','USD/CNH','USD/HKD','USD/SGD','USD/INR','USD/KRW','USD/BRL','USD/CZK','USD/HUF','USD/ILS','USD/SAR','USD/AED','USD/CLP','USD/COP','USD/ARS','USD/PHP','USD/IDR','USD/THB','USD/TWD','USD/MYR','USD/VND','USD/BGN','USD/HRK','USD/RON','USD/QAR','USD/EGP','USD/KZT','USD/PKR','USD/NPR','USD/BDT','USD/LKR','USD/MAD','USD/TND','USD/DZD','USD/MUR','USD/OMR','USD/BHD','USD/KWD','USD/BMD','USD/BBD','USD/BSD','USD/CRC','USD/DOP','USD/GHS','USD/GEL','USD/GMD','USD/GNF','USD/GTQ','USD/HNL','USD/JMD','USD/KES','USD/LAK','USD/LSL','USD/MWK','USD/MZN','USD/NAD','USD/NIO','USD/RWF','USD/SCR','USD/SLL','USD/SOS','USD/SZL','USD/TZS','USD/UGX','USD/UYU','USD/UZS','USD/XAF','USD/XOF','USD/ZMW','USD/AOA','USD/BYN','USD/BOB','USD/FJD','USD/GYD','USD/LBP','USD/LRD','USD/MNT','USD/MOP','USD/MVR','USD/PEN','USD/PGK','USD/SBD','USD/SHP','USD/SRD','USD/TTD','USD/XPF'
];

const commodityBase = [
  'XAU/USD','XAG/USD','XPT/USD','XPD/USD','WTI','BRENT','NG','CORN','SOYBEAN','WHEAT','COFFEE','COCOA','SUGAR','COTTON','LIVE_CATTLE','LEAN_HOGS','ALUMINUM','COPPER','NICKEL','ZINC','LEAD','TIN','URANIUM','LUMBER','RBOB_GAS','HEATING_OIL','COAL','RICE','MILK','ORANGE_JUICE','RUBBER','PALM_OIL','ETHANOL','OATS','FEEDER_CATTLE','GOLD_EUR','SILVER_EUR','GOLD_TRY','SILVER_TRY','PLATINUM_TRY','PALLADIUM_TRY','IRON_ORE','STEEL','POLYPROPYLENE','POLYETHYLENE','BRN/TRY','WTI/TRY','NG/TRY','CORN/TRY','WHEAT/TRY','COFFEE/TRY','COCOA/TRY','SUGAR/TRY','COTTON/TRY','ALUMINUM/TRY','COPPER/TRY','ZINC/TRY','NICKEL/TRY','SOYBEAN/TRY','OATS/TRY','RICE/TRY','MILK/TRY','RUBBER/TRY','PALM/TRY','ETHANOL/TRY','COAL/TRY','LUMBER/TRY','HEATING_OIL/TRY','URANIUM/TRY','GOLD/GBP','SILVER/GBP','GOLD/JPY','SILVER/JPY','GOLD/CAD','SILVER/CAD','GOLD/AUD','SILVER/AUD','GOLD/NZD','SILVER/NZD','GOLD/CHF','SILVER/CHF','GOLD/CNH','SILVER/CNH','GOLD/HKD','SILVER/HKD','GOLD/SGD','SILVER/SGD','GOLD/INR','SILVER/INR','GOLD/BRL','SILVER/BRL','GOLD/ZAR','SILVER/ZAR','GOLD/RUB','SILVER/RUB','GOLD/MXN','SILVER/MXN','GOLD/PLN','SILVER/PLN','GOLD/TRY_GR','SILVER/TRY_GR','PETROL_OFISI','TMO_BUĞDAY','TMO_ARPA','TMO_MISIR','TMO_CAVDAR'
];

const intlStockBase = [
  'AAPL','MSFT','AMZN','GOOGL','GOOG','META','TSLA','NVDA','BRK.B','LLY','JPM','V','UNH','MA','XOM','AVGO','PG','JNJ','WMT','HD','CVX','MRK','PEP','ABBV','COST','KO','ADBE','MCD','PFE','CRM','CSCO','BAC','LIN','TMO','ACN','DHR','TXN','ABT','AMD','CMCSA','NFLX','NKE','INTC','ORCL','DIS','AMGN','VZ','UPS','PM','IBM','RTX','BMY','MS','QCOM','CAT','LOW','SBUX','GS','GE','AMAT','BLK','NOW','AXP','SPGI','PLD','MDT','LMT','ADI','HON','C','BKNG','DE','CB','MO','BA','MU','ADI','ELV','ADP','CME','CI','SYK','BDX','MMC','USB','ZTS','TGT','CVS','SO','DUK','PNC','CSX','SCHW','COP','INTU','GILD','NSC','EQIX','ITW','ISRG','EOG','PGR','ICE','CL','TFC','WM','SHW','ETN','APD','FDX','LRCX','EMR','MPC','MCO','PH','PSA','KDP','NOC','ORLY','CARR','AON','REGN','MAR','MRNA','KHC','NXPI','HUM','ROP','AEP','DHI','KMB','GIS','TRV','SYY','STZ','PAYX','MSI','MCK','CRWD','SNOW','DKNG','UBER','ROKU','SQ','TDOC','OKTA','ZS','PANW','TEAM','NET','DDOG','DOCU','PINS','BIDU','BABA','JD','PDD','NTES','SHOP','SE','MELI','BHP','RIO','SHEL','BP','TOT','SONY','TM','HMC','RACE','VOW3','SAP','ASML','NVS','NESN','RHHBY','OR','UL','BUD'
];

export const marketBuckets = {
  crypto: padTo200(cryptoBase),
  tr_equities: padTo200(trStockBase),
  forex: padTo200(forexBase),
  commodities: padTo200(commodityBase),
  intl_equities: padTo200(intlStockBase)
};
